check50:
  checks:
    prints yppah for happy:
      - run: python3 reverse.py
        stdin: happy
        stdout: yppah
    prints nohtyP for Python:
      - run: python3 reverse.py
        stdin: Python
        stdout: nohtyP
    prints empty string for empty string:
      - run: python3 reverse.py
        stdin: 
        stdout: 
    prints a for a:
      - run: python3 reverse.py
        stdin: a
        stdout: a
